gitpulse:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: postgres
      password: postgres
      dbname: gitpulse
      schema: public
      threads: 4
  target: dev
